### ISSUE TITLE
define readme file

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/Calender#3]
add a description about this project. if you need additional information ask me

**Comment by rfoldbirk** [comment]
Sure, but what is the idea behind the program?

**Comment by sabesansathananthan** [comment]
embed google calendar in this calendar layout.

**Comment by sabesansathananthan** [comment]
@sampaththeman  thank you
please read and clap this story if you like  https://medium.com/@sabesan96/how-to-contribute-to-open-source-6c1246cd7536
